# Generated by Django 4.1 on 2022-08-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoUsuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigoAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('numDocumento', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('codigoCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codigoProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('numDocumento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('codigoTutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('numDocumento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('codigoRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('codigoAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_alumno', to='Institucion.alumno')),
                ('codigoCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cursos', to='Institucion.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Honorarios',
            fields=[
                ('codigoHonorario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('codigoProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_profesor_h', to='Institucion.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='fk_codigoProfesor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_profesor', to='Institucion.profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='codigoTutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_alumno', to='Institucion.tutor'),
        ),
    ]
