# Generated by Django 4.1 on 2022-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('id_estudiante', models.IntegerField()),
                ('celular', models.CharField(max_length=9)),
                ('genero', models.CharField(max_length=1)),
                ('turno', models.CharField(max_length=20)),
                ('grado', models.IntegerField(max_length=1)),
            ],
        ),
    ]
